package IBA_J.ConvertListFiles.FrameC;

import IBA_J.ConvertListFiles.ActionsC.ActionsC;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.AbstractButton;
import javax.swing.ButtonGroup;
import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.SwingConstants;

/**
 * This class is the frame to configure the settings when opening a lst file
 */
public class FrameC extends javax.swing.JFrame {

    /** Creates new form FrameC */
    public FrameC() {
        initComponents();
        // TODO : checkCheckBox() to replace act.initFlags();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        GridBagConstraints gridBagConstraints;

        buttonGroup1 = new ButtonGroup();
        buttonGroup2 = new ButtonGroup();
        buttonGroup3 = new ButtonGroup();
        buttonGroup4 = new ButtonGroup();
        buttonGroup5 = new ButtonGroup();
        buttonGroup6 = new ButtonGroup();
        buttonGroup7 = new ButtonGroup();
        buttonGroup8 = new ButtonGroup();
        buttonGroup9 = new ButtonGroup();
        buttonGroup10 = new ButtonGroup();
        buttonGroup11 = new ButtonGroup();
        buttonGroup12 = new ButtonGroup();
        buttonGroup13 = new ButtonGroup();
        buttonGroup14 = new ButtonGroup();
        buttonGroup15 = new ButtonGroup();
        buttonGroup16 = new ButtonGroup();
        jPanelA = new JPanel();
        jPanelB = new JPanel();
        jPanel1 = new JPanel();
        jLabel8 = new JLabel();
        jRadioButton1 = new JRadioButton();
        jRadioButton2 = new JRadioButton();
        jRadioButton3 = new JRadioButton();
        jRadioButton4 = new JRadioButton();
        jRadioButton5 = new JRadioButton();
        jRadioButton6 = new JRadioButton();
        jLabel10 = new JLabel();
        jLabel7 = new JLabel();
        jLabel6 = new JLabel();
        jLabel5 = new JLabel();
        jLabel4 = new JLabel();
        jLabel3 = new JLabel();
        jLabel2 = new JLabel();
        jPanel2 = new JPanel();
        jLabel9 = new JLabel();
        jRadioButton7 = new JRadioButton();
        jRadioButton8 = new JRadioButton();
        jRadioButton9 = new JRadioButton();
        jRadioButton10 = new JRadioButton();
        jRadioButton11 = new JRadioButton();
        jRadioButton12 = new JRadioButton();
        jPanel3 = new JPanel();
        jLabel11 = new JLabel();
        jRadioButton13 = new JRadioButton();
        jRadioButton14 = new JRadioButton();
        jRadioButton15 = new JRadioButton();
        jRadioButton16 = new JRadioButton();
        jRadioButton17 = new JRadioButton();
        jRadioButton18 = new JRadioButton();
        jPanel4 = new JPanel();
        jLabel12 = new JLabel();
        jRadioButton19 = new JRadioButton();
        jRadioButton20 = new JRadioButton();
        jRadioButton21 = new JRadioButton();
        jRadioButton22 = new JRadioButton();
        jRadioButton23 = new JRadioButton();
        jRadioButton24 = new JRadioButton();
        jPanel5 = new JPanel();
        jLabel13 = new JLabel();
        jRadioButton25 = new JRadioButton();
        jRadioButton26 = new JRadioButton();
        jRadioButton27 = new JRadioButton();
        jRadioButton28 = new JRadioButton();
        jRadioButton29 = new JRadioButton();
        jRadioButton30 = new JRadioButton();
        jPanel6 = new JPanel();
        jLabel14 = new JLabel();
        jRadioButton31 = new JRadioButton();
        jRadioButton32 = new JRadioButton();
        jRadioButton33 = new JRadioButton();
        jRadioButton34 = new JRadioButton();
        jRadioButton35 = new JRadioButton();
        jRadioButton36 = new JRadioButton();
        jPanel7 = new JPanel();
        jLabel15 = new JLabel();
        jRadioButton37 = new JRadioButton();
        jRadioButton38 = new JRadioButton();
        jRadioButton39 = new JRadioButton();
        jRadioButton40 = new JRadioButton();
        jRadioButton41 = new JRadioButton();
        jRadioButton42 = new JRadioButton();
        jPanel8 = new JPanel();
        jLabel17 = new JLabel();
        jRadioButton43 = new JRadioButton();
        jRadioButton44 = new JRadioButton();
        jRadioButton45 = new JRadioButton();
        jRadioButton46 = new JRadioButton();
        jRadioButton47 = new JRadioButton();
        jRadioButton48 = new JRadioButton();
        jPanel9 = new JPanel();
        jLabel21 = new JLabel();
        jRadioButton49 = new JRadioButton();
        jRadioButton50 = new JRadioButton();
        jRadioButton51 = new JRadioButton();
        jRadioButton52 = new JRadioButton();
        jRadioButton53 = new JRadioButton();
        jRadioButton54 = new JRadioButton();
        jPanel10 = new JPanel();
        jLabel22 = new JLabel();
        jRadioButton55 = new JRadioButton();
        jRadioButton56 = new JRadioButton();
        jRadioButton57 = new JRadioButton();
        jRadioButton58 = new JRadioButton();
        jRadioButton59 = new JRadioButton();
        jRadioButton60 = new JRadioButton();
        jPanel11 = new JPanel();
        jLabel23 = new JLabel();
        jRadioButton61 = new JRadioButton();
        jRadioButton62 = new JRadioButton();
        jRadioButton63 = new JRadioButton();
        jRadioButton64 = new JRadioButton();
        jRadioButton65 = new JRadioButton();
        jRadioButton66 = new JRadioButton();
        jPanel12 = new JPanel();
        jLabel24 = new JLabel();
        jRadioButton67 = new JRadioButton();
        jRadioButton68 = new JRadioButton();
        jRadioButton69 = new JRadioButton();
        jRadioButton70 = new JRadioButton();
        jRadioButton71 = new JRadioButton();
        jRadioButton72 = new JRadioButton();
        jPanel13 = new JPanel();
        jLabel25 = new JLabel();
        jRadioButton73 = new JRadioButton();
        jRadioButton74 = new JRadioButton();
        jRadioButton75 = new JRadioButton();
        jRadioButton76 = new JRadioButton();
        jRadioButton77 = new JRadioButton();
        jRadioButton78 = new JRadioButton();
        jPanel14 = new JPanel();
        jLabel26 = new JLabel();
        jRadioButton79 = new JRadioButton();
        jRadioButton80 = new JRadioButton();
        jRadioButton81 = new JRadioButton();
        jRadioButton82 = new JRadioButton();
        jRadioButton83 = new JRadioButton();
        jRadioButton84 = new JRadioButton();
        jPanel15 = new JPanel();
        jLabel27 = new JLabel();
        jRadioButton85 = new JRadioButton();
        jRadioButton86 = new JRadioButton();
        jRadioButton87 = new JRadioButton();
        jRadioButton88 = new JRadioButton();
        jRadioButton89 = new JRadioButton();
        jRadioButton90 = new JRadioButton();
        jPanel16 = new JPanel();
        jLabel28 = new JLabel();
        jRadioButton91 = new JRadioButton();
        jRadioButton92 = new JRadioButton();
        jRadioButton93 = new JRadioButton();
        jRadioButton94 = new JRadioButton();
        jRadioButton95 = new JRadioButton();
        jRadioButton96 = new JRadioButton();
        jLabel1 = new JLabel();
        jPanelC = new JPanel();
        jLabel16 = new JLabel();
        jCheckBox1 = new JCheckBox();
        jCheckBox2 = new JCheckBox();
        jCheckBox3 = new JCheckBox();
        jCheckBox4 = new JCheckBox();
        jLabel18 = new JLabel();
        jCheckBox5 = new JCheckBox();
        jLabel19 = new JLabel();
        jCheckBox6 = new JCheckBox();
        jCheckBox7 = new JCheckBox();
        jLabel20 = new JLabel();
        jCheckBox8 = new JCheckBox();
        jCheckBox9 = new JCheckBox();
        jCheckBox10 = new JCheckBox();
        jCheckBox11 = new JCheckBox();
        jCheckBox12 = new JCheckBox();

        setTitle("Data conversion Options  (07/2014)");
        setName("Form"); // NOI18N
        getContentPane().setLayout(new GridBagLayout());

        jPanelA.setName("jPanelA"); // NOI18N
        jPanelA.setLayout(new GridBagLayout());

        jPanelB.setName("jPanelB"); // NOI18N
        jPanelB.setLayout(new GridBagLayout());

        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setLayout(new GridBagLayout());

        jLabel8.setText("1A");
        jLabel8.setName("jLabel8"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        jPanel1.add(jLabel8, gridBagConstraints);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setName("jRadioButton1"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = GridBagConstraints.BOTH;
        gridBagConstraints.anchor = GridBagConstraints.BASELINE;
        jPanel1.add(jRadioButton1, gridBagConstraints);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setName("jRadioButton2"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = GridBagConstraints.BASELINE;
        jPanel1.add(jRadioButton2, gridBagConstraints);

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setName("jRadioButton3"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = GridBagConstraints.BASELINE;
        jPanel1.add(jRadioButton3, gridBagConstraints);

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setName("jRadioButton4"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = GridBagConstraints.BASELINE;
        jPanel1.add(jRadioButton4, gridBagConstraints);

        buttonGroup1.add(jRadioButton5);
        jRadioButton5.setName("jRadioButton5"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = GridBagConstraints.BASELINE;
        jPanel1.add(jRadioButton5, gridBagConstraints);

        buttonGroup1.add(jRadioButton6);
        jRadioButton6.setSelected(true);
        jRadioButton6.setName("jRadioButton6"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = GridBagConstraints.BASELINE;
        jPanel1.add(jRadioButton6, gridBagConstraints);

        jLabel10.setText("Scan. Y");
        jLabel10.setName("jLabel10"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = GridBagConstraints.WEST;
        jPanel1.add(jLabel10, gridBagConstraints);

        jLabel7.setText("None");
        jLabel7.setName("jLabel7"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = GridBagConstraints.WEST;
        jPanel1.add(jLabel7, gridBagConstraints);

        jLabel6.setText("Scan. X");
        jLabel6.setName("jLabel6"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = GridBagConstraints.WEST;
        jPanel1.add(jLabel6, gridBagConstraints);

        jLabel5.setText("PIXE");
        jLabel5.setName("jLabel5"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = GridBagConstraints.WEST;
        jPanel1.add(jLabel5, gridBagConstraints);

        jLabel4.setText("STIM");
        jLabel4.setName("jLabel4"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = GridBagConstraints.WEST;
        jPanel1.add(jLabel4, gridBagConstraints);

        jLabel3.setText("RBS");
        jLabel3.setName("jLabel3"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = GridBagConstraints.LINE_START;
        jPanel1.add(jLabel3, gridBagConstraints);

        jLabel2.setText("ADC");
        jLabel2.setName("jLabel2"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = GridBagConstraints.WEST;
        jPanel1.add(jLabel2, gridBagConstraints);

        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 7;
        gridBagConstraints.anchor = GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new Insets(10, 0, 0, 0);
        jPanelB.add(jPanel1, gridBagConstraints);

        jPanel2.setName("jPanel2"); // NOI18N
        jPanel2.setLayout(new GridBagLayout());

        jLabel9.setText("1B");
        jLabel9.setName("jLabel9"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        jPanel2.add(jLabel9, gridBagConstraints);

        buttonGroup2.add(jRadioButton7);
        jRadioButton7.setName("jRadioButton7"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = GridBagConstraints.BOTH;
        jPanel2.add(jRadioButton7, gridBagConstraints);

        buttonGroup2.add(jRadioButton8);
        jRadioButton8.setName("jRadioButton8"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        jPanel2.add(jRadioButton8, gridBagConstraints);

        buttonGroup2.add(jRadioButton9);
        jRadioButton9.setName("jRadioButton9"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        jPanel2.add(jRadioButton9, gridBagConstraints);

        buttonGroup2.add(jRadioButton10);
        jRadioButton10.setName("jRadioButton10"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        jPanel2.add(jRadioButton10, gridBagConstraints);

        buttonGroup2.add(jRadioButton11);
        jRadioButton11.setName("jRadioButton11"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        jPanel2.add(jRadioButton11, gridBagConstraints);

        buttonGroup2.add(jRadioButton12);
        jRadioButton12.setSelected(true);
        jRadioButton12.setName("jRadioButton12"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        jPanel2.add(jRadioButton12, gridBagConstraints);

        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 7;
        gridBagConstraints.anchor = GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new Insets(10, 0, 0, 0);
        jPanelB.add(jPanel2, gridBagConstraints);

        jPanel3.setName("jPanel3"); // NOI18N
        jPanel3.setLayout(new GridBagLayout());

        jLabel11.setText("1C");
        jLabel11.setName("jLabel11"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        jPanel3.add(jLabel11, gridBagConstraints);

        buttonGroup3.add(jRadioButton13);
        jRadioButton13.setName("jRadioButton13"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = GridBagConstraints.BOTH;
        jPanel3.add(jRadioButton13, gridBagConstraints);

        buttonGroup3.add(jRadioButton14);
        jRadioButton14.setName("jRadioButton14"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        jPanel3.add(jRadioButton14, gridBagConstraints);

        buttonGroup3.add(jRadioButton15);
        jRadioButton15.setName("jRadioButton15"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        jPanel3.add(jRadioButton15, gridBagConstraints);

        buttonGroup3.add(jRadioButton16);
        jRadioButton16.setName("jRadioButton16"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        jPanel3.add(jRadioButton16, gridBagConstraints);

        buttonGroup3.add(jRadioButton17);
        jRadioButton17.setName("jRadioButton17"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        jPanel3.add(jRadioButton17, gridBagConstraints);

        buttonGroup3.add(jRadioButton18);
        jRadioButton18.setSelected(true);
        jRadioButton18.setName("jRadioButton18"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        jPanel3.add(jRadioButton18, gridBagConstraints);

        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 7;
        gridBagConstraints.anchor = GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new Insets(10, 0, 0, 0);
        jPanelB.add(jPanel3, gridBagConstraints);

        jPanel4.setName("jPanel4"); // NOI18N
        jPanel4.setLayout(new GridBagLayout());

        jLabel12.setText("1D");
        jLabel12.setName("jLabel12"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        jPanel4.add(jLabel12, gridBagConstraints);

        buttonGroup4.add(jRadioButton19);
        jRadioButton19.setName("jRadioButton19"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = GridBagConstraints.BOTH;
        jPanel4.add(jRadioButton19, gridBagConstraints);

        buttonGroup4.add(jRadioButton20);
        jRadioButton20.setName("jRadioButton20"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        jPanel4.add(jRadioButton20, gridBagConstraints);

        buttonGroup4.add(jRadioButton21);
        jRadioButton21.setName("jRadioButton21"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        jPanel4.add(jRadioButton21, gridBagConstraints);

        buttonGroup4.add(jRadioButton22);
        jRadioButton22.setName("jRadioButton22"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        jPanel4.add(jRadioButton22, gridBagConstraints);

        buttonGroup4.add(jRadioButton23);
        jRadioButton23.setName("jRadioButton23"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        jPanel4.add(jRadioButton23, gridBagConstraints);

        buttonGroup4.add(jRadioButton24);
        jRadioButton24.setSelected(true);
        jRadioButton24.setName("jRadioButton24"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        jPanel4.add(jRadioButton24, gridBagConstraints);

        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 7;
        gridBagConstraints.anchor = GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new Insets(10, 0, 0, 0);
        jPanelB.add(jPanel4, gridBagConstraints);

        jPanel5.setName("jPanel5"); // NOI18N
        jPanel5.setLayout(new GridBagLayout());

        jLabel13.setText("2A");
        jLabel13.setName("jLabel13"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        jPanel5.add(jLabel13, gridBagConstraints);

        buttonGroup5.add(jRadioButton25);
        jRadioButton25.setName("jRadioButton25"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = GridBagConstraints.BOTH;
        jPanel5.add(jRadioButton25, gridBagConstraints);

        buttonGroup5.add(jRadioButton26);
        jRadioButton26.setName("jRadioButton26"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        jPanel5.add(jRadioButton26, gridBagConstraints);

        buttonGroup5.add(jRadioButton27);
        jRadioButton27.setName("jRadioButton27"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        jPanel5.add(jRadioButton27, gridBagConstraints);

        buttonGroup5.add(jRadioButton28);
        jRadioButton28.setName("jRadioButton28"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        jPanel5.add(jRadioButton28, gridBagConstraints);

        buttonGroup5.add(jRadioButton29);
        jRadioButton29.setName("jRadioButton29"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        jPanel5.add(jRadioButton29, gridBagConstraints);

        buttonGroup5.add(jRadioButton30);
        jRadioButton30.setSelected(true);
        jRadioButton30.setName("jRadioButton30"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        jPanel5.add(jRadioButton30, gridBagConstraints);

        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 7;
        gridBagConstraints.anchor = GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new Insets(10, 0, 0, 0);
        jPanelB.add(jPanel5, gridBagConstraints);

        jPanel6.setName("jPanel6"); // NOI18N
        jPanel6.setLayout(new GridBagLayout());

        jLabel14.setText("2B");
        jLabel14.setName("jLabel14"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        jPanel6.add(jLabel14, gridBagConstraints);

        buttonGroup6.add(jRadioButton31);
        jRadioButton31.setName("jRadioButton31"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = GridBagConstraints.BOTH;
        jPanel6.add(jRadioButton31, gridBagConstraints);

        buttonGroup6.add(jRadioButton32);
        jRadioButton32.setName("jRadioButton32"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        jPanel6.add(jRadioButton32, gridBagConstraints);

        buttonGroup6.add(jRadioButton33);
        jRadioButton33.setName("jRadioButton33"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        jPanel6.add(jRadioButton33, gridBagConstraints);

        buttonGroup6.add(jRadioButton34);
        jRadioButton34.setName("jRadioButton34"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        jPanel6.add(jRadioButton34, gridBagConstraints);

        buttonGroup6.add(jRadioButton35);
        jRadioButton35.setName("jRadioButton35"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        jPanel6.add(jRadioButton35, gridBagConstraints);

        buttonGroup6.add(jRadioButton36);
        jRadioButton36.setSelected(true);
        jRadioButton36.setName("jRadioButton36"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        jPanel6.add(jRadioButton36, gridBagConstraints);

        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 7;
        gridBagConstraints.anchor = GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new Insets(10, 0, 0, 0);
        jPanelB.add(jPanel6, gridBagConstraints);

        jPanel7.setName("jPanel7"); // NOI18N
        jPanel7.setLayout(new GridBagLayout());

        jLabel15.setText("2C");
        jLabel15.setName("jLabel15"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        jPanel7.add(jLabel15, gridBagConstraints);

        buttonGroup7.add(jRadioButton37);
        jRadioButton37.setName("jRadioButton37"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = GridBagConstraints.BOTH;
        jPanel7.add(jRadioButton37, gridBagConstraints);

        buttonGroup7.add(jRadioButton38);
        jRadioButton38.setName("jRadioButton38"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        jPanel7.add(jRadioButton38, gridBagConstraints);

        buttonGroup7.add(jRadioButton39);
        jRadioButton39.setName("jRadioButton39"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        jPanel7.add(jRadioButton39, gridBagConstraints);

        buttonGroup7.add(jRadioButton40);
        jRadioButton40.setSelected(true);
        jRadioButton40.setName("jRadioButton40"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        jPanel7.add(jRadioButton40, gridBagConstraints);

        buttonGroup7.add(jRadioButton41);
        jRadioButton41.setName("jRadioButton41"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        jPanel7.add(jRadioButton41, gridBagConstraints);

        buttonGroup7.add(jRadioButton42);
        jRadioButton42.setName("jRadioButton42"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        jPanel7.add(jRadioButton42, gridBagConstraints);

        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 7;
        gridBagConstraints.anchor = GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new Insets(10, 0, 0, 0);
        jPanelB.add(jPanel7, gridBagConstraints);

        jPanel8.setName("jPanel8"); // NOI18N
        jPanel8.setLayout(new GridBagLayout());

        jLabel17.setText("2D");
        jLabel17.setName("jLabel17"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        jPanel8.add(jLabel17, gridBagConstraints);

        buttonGroup8.add(jRadioButton43);
        jRadioButton43.setName("jRadioButton43"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = GridBagConstraints.BOTH;
        jPanel8.add(jRadioButton43, gridBagConstraints);

        buttonGroup8.add(jRadioButton44);
        jRadioButton44.setName("jRadioButton44"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        jPanel8.add(jRadioButton44, gridBagConstraints);

        buttonGroup8.add(jRadioButton45);
        jRadioButton45.setName("jRadioButton45"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        jPanel8.add(jRadioButton45, gridBagConstraints);

        buttonGroup8.add(jRadioButton46);
        jRadioButton46.setName("jRadioButton46"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        jPanel8.add(jRadioButton46, gridBagConstraints);

        buttonGroup8.add(jRadioButton47);
        jRadioButton47.setSelected(true);
        jRadioButton47.setName("jRadioButton47"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        jPanel8.add(jRadioButton47, gridBagConstraints);

        buttonGroup8.add(jRadioButton48);
        jRadioButton48.setName("jRadioButton48"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        jPanel8.add(jRadioButton48, gridBagConstraints);

        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 7;
        gridBagConstraints.anchor = GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new Insets(10, 0, 0, 0);
        jPanelB.add(jPanel8, gridBagConstraints);

        jPanel9.setName("jPanel9"); // NOI18N
        jPanel9.setLayout(new GridBagLayout());

        jLabel21.setText("3A");
        jLabel21.setName("jLabel21"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        jPanel9.add(jLabel21, gridBagConstraints);

        buttonGroup9.add(jRadioButton49);
        jRadioButton49.setName("jRadioButton49"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = GridBagConstraints.BOTH;
        jPanel9.add(jRadioButton49, gridBagConstraints);

        buttonGroup9.add(jRadioButton50);
        jRadioButton50.setName("jRadioButton50"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        jPanel9.add(jRadioButton50, gridBagConstraints);

        buttonGroup9.add(jRadioButton51);
        jRadioButton51.setSelected(true);
        jRadioButton51.setName("jRadioButton51"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        jPanel9.add(jRadioButton51, gridBagConstraints);

        buttonGroup9.add(jRadioButton52);
        jRadioButton52.setName("jRadioButton52"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        jPanel9.add(jRadioButton52, gridBagConstraints);

        buttonGroup9.add(jRadioButton53);
        jRadioButton53.setName("jRadioButton53"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        jPanel9.add(jRadioButton53, gridBagConstraints);

        buttonGroup9.add(jRadioButton54);
        jRadioButton54.setName("jRadioButton54"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        jPanel9.add(jRadioButton54, gridBagConstraints);

        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 7;
        gridBagConstraints.anchor = GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new Insets(10, 0, 0, 0);
        jPanelB.add(jPanel9, gridBagConstraints);

        jPanel10.setName("jPanel10"); // NOI18N
        jPanel10.setLayout(new GridBagLayout());

        jLabel22.setText("3B");
        jLabel22.setName("jLabel22"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        jPanel10.add(jLabel22, gridBagConstraints);

        buttonGroup10.add(jRadioButton55);
        jRadioButton55.setName("jRadioButton55"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = GridBagConstraints.BOTH;
        jPanel10.add(jRadioButton55, gridBagConstraints);

        buttonGroup10.add(jRadioButton56);
        jRadioButton56.setName("jRadioButton56"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        jPanel10.add(jRadioButton56, gridBagConstraints);

        buttonGroup10.add(jRadioButton57);
        jRadioButton57.setSelected(true);
        jRadioButton57.setName("jRadioButton57"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        jPanel10.add(jRadioButton57, gridBagConstraints);

        buttonGroup10.add(jRadioButton58);
        jRadioButton58.setName("jRadioButton58"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        jPanel10.add(jRadioButton58, gridBagConstraints);

        buttonGroup10.add(jRadioButton59);
        jRadioButton59.setName("jRadioButton59"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        jPanel10.add(jRadioButton59, gridBagConstraints);

        buttonGroup10.add(jRadioButton60);
        jRadioButton60.setName("jRadioButton60"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        jPanel10.add(jRadioButton60, gridBagConstraints);

        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 7;
        gridBagConstraints.anchor = GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new Insets(10, 0, 0, 0);
        jPanelB.add(jPanel10, gridBagConstraints);

        jPanel11.setName("jPanel11"); // NOI18N
        jPanel11.setLayout(new GridBagLayout());

        jLabel23.setText("3C");
        jLabel23.setName("jLabel23"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        jPanel11.add(jLabel23, gridBagConstraints);

        buttonGroup11.add(jRadioButton61);
        jRadioButton61.setName("jRadioButton61"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = GridBagConstraints.BOTH;
        jPanel11.add(jRadioButton61, gridBagConstraints);

        buttonGroup11.add(jRadioButton62);
        jRadioButton62.setName("jRadioButton62"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        jPanel11.add(jRadioButton62, gridBagConstraints);

        buttonGroup11.add(jRadioButton63);
        jRadioButton63.setName("jRadioButton63"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        jPanel11.add(jRadioButton63, gridBagConstraints);

        buttonGroup11.add(jRadioButton64);
        jRadioButton64.setName("jRadioButton64"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        jPanel11.add(jRadioButton64, gridBagConstraints);

        buttonGroup11.add(jRadioButton65);
        jRadioButton65.setName("jRadioButton65"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        jPanel11.add(jRadioButton65, gridBagConstraints);

        buttonGroup11.add(jRadioButton66);
        jRadioButton66.setSelected(true);
        jRadioButton66.setName("jRadioButton66"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        jPanel11.add(jRadioButton66, gridBagConstraints);

        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 7;
        gridBagConstraints.anchor = GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new Insets(10, 0, 0, 0);
        jPanelB.add(jPanel11, gridBagConstraints);

        jPanel12.setName("jPanel12"); // NOI18N
        jPanel12.setLayout(new GridBagLayout());

        jLabel24.setText("3D");
        jLabel24.setName("jLabel24"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        jPanel12.add(jLabel24, gridBagConstraints);

        buttonGroup12.add(jRadioButton67);
        jRadioButton67.setName("jRadioButton67"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = GridBagConstraints.BOTH;
        jPanel12.add(jRadioButton67, gridBagConstraints);

        buttonGroup12.add(jRadioButton68);
        jRadioButton68.setName("jRadioButton68"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        jPanel12.add(jRadioButton68, gridBagConstraints);

        buttonGroup12.add(jRadioButton69);
        jRadioButton69.setName("jRadioButton69"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        jPanel12.add(jRadioButton69, gridBagConstraints);

        buttonGroup12.add(jRadioButton70);
        jRadioButton70.setName("jRadioButton70"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        jPanel12.add(jRadioButton70, gridBagConstraints);

        buttonGroup12.add(jRadioButton71);
        jRadioButton71.setName("jRadioButton71"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        jPanel12.add(jRadioButton71, gridBagConstraints);

        buttonGroup12.add(jRadioButton72);
        jRadioButton72.setSelected(true);
        jRadioButton72.setName("jRadioButton72"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        jPanel12.add(jRadioButton72, gridBagConstraints);

        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 7;
        gridBagConstraints.anchor = GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new Insets(10, 0, 0, 0);
        jPanelB.add(jPanel12, gridBagConstraints);

        jPanel13.setName("jPanel13"); // NOI18N
        jPanel13.setLayout(new GridBagLayout());

        jLabel25.setText("4A");
        jLabel25.setName("jLabel25"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        jPanel13.add(jLabel25, gridBagConstraints);

        buttonGroup13.add(jRadioButton73);
        jRadioButton73.setName("jRadioButton73"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = GridBagConstraints.BOTH;
        jPanel13.add(jRadioButton73, gridBagConstraints);

        buttonGroup13.add(jRadioButton74);
        jRadioButton74.setName("jRadioButton74"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        jPanel13.add(jRadioButton74, gridBagConstraints);

        buttonGroup13.add(jRadioButton75);
        jRadioButton75.setName("jRadioButton75"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        jPanel13.add(jRadioButton75, gridBagConstraints);

        buttonGroup13.add(jRadioButton76);
        jRadioButton76.setName("jRadioButton76"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        jPanel13.add(jRadioButton76, gridBagConstraints);

        buttonGroup13.add(jRadioButton77);
        jRadioButton77.setName("jRadioButton77"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        jPanel13.add(jRadioButton77, gridBagConstraints);

        buttonGroup13.add(jRadioButton78);
        jRadioButton78.setSelected(true);
        jRadioButton78.setName("jRadioButton78"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        jPanel13.add(jRadioButton78, gridBagConstraints);

        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 12;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 7;
        gridBagConstraints.anchor = GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new Insets(10, 0, 0, 0);
        jPanelB.add(jPanel13, gridBagConstraints);

        jPanel14.setName("jPanel14"); // NOI18N
        jPanel14.setLayout(new GridBagLayout());

        jLabel26.setText("4B");
        jLabel26.setName("jLabel26"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        jPanel14.add(jLabel26, gridBagConstraints);

        buttonGroup14.add(jRadioButton79);
        jRadioButton79.setName("jRadioButton79"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = GridBagConstraints.BOTH;
        jPanel14.add(jRadioButton79, gridBagConstraints);

        buttonGroup14.add(jRadioButton80);
        jRadioButton80.setName("jRadioButton80"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        jPanel14.add(jRadioButton80, gridBagConstraints);

        buttonGroup14.add(jRadioButton81);
        jRadioButton81.setName("jRadioButton81"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        jPanel14.add(jRadioButton81, gridBagConstraints);

        buttonGroup14.add(jRadioButton82);
        jRadioButton82.setName("jRadioButton82"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        jPanel14.add(jRadioButton82, gridBagConstraints);

        buttonGroup14.add(jRadioButton83);
        jRadioButton83.setName("jRadioButton83"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        jPanel14.add(jRadioButton83, gridBagConstraints);

        buttonGroup14.add(jRadioButton84);
        jRadioButton84.setSelected(true);
        jRadioButton84.setName("jRadioButton84"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        jPanel14.add(jRadioButton84, gridBagConstraints);

        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 13;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 7;
        gridBagConstraints.anchor = GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new Insets(10, 0, 0, 0);
        jPanelB.add(jPanel14, gridBagConstraints);

        jPanel15.setName("jPanel15"); // NOI18N
        jPanel15.setLayout(new GridBagLayout());

        jLabel27.setText("4C");
        jLabel27.setName("jLabel27"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        jPanel15.add(jLabel27, gridBagConstraints);

        buttonGroup15.add(jRadioButton85);
        jRadioButton85.setName("jRadioButton85"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = GridBagConstraints.BOTH;
        jPanel15.add(jRadioButton85, gridBagConstraints);

        buttonGroup15.add(jRadioButton86);
        jRadioButton86.setSelected(true);
        jRadioButton86.setName("jRadioButton86"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        jPanel15.add(jRadioButton86, gridBagConstraints);

        buttonGroup15.add(jRadioButton87);
        jRadioButton87.setName("jRadioButton87"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        jPanel15.add(jRadioButton87, gridBagConstraints);

        buttonGroup15.add(jRadioButton88);
        jRadioButton88.setName("jRadioButton88"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        jPanel15.add(jRadioButton88, gridBagConstraints);

        buttonGroup15.add(jRadioButton89);
        jRadioButton89.setName("jRadioButton89"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        jPanel15.add(jRadioButton89, gridBagConstraints);

        buttonGroup15.add(jRadioButton90);
        jRadioButton90.setName("jRadioButton90"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        jPanel15.add(jRadioButton90, gridBagConstraints);

        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 14;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 7;
        gridBagConstraints.anchor = GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new Insets(10, 0, 0, 0);
        jPanelB.add(jPanel15, gridBagConstraints);

        jPanel16.setName("jPanel16"); // NOI18N
        jPanel16.setLayout(new GridBagLayout());

        jLabel28.setText("4D");
        jLabel28.setName("jLabel28"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        jPanel16.add(jLabel28, gridBagConstraints);

        buttonGroup16.add(jRadioButton91);
        jRadioButton91.setName("jRadioButton91"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = GridBagConstraints.BOTH;
        jPanel16.add(jRadioButton91, gridBagConstraints);

        buttonGroup16.add(jRadioButton92);
        jRadioButton92.setName("jRadioButton92"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        jPanel16.add(jRadioButton92, gridBagConstraints);

        buttonGroup16.add(jRadioButton93);
        jRadioButton93.setName("jRadioButton93"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        jPanel16.add(jRadioButton93, gridBagConstraints);

        buttonGroup16.add(jRadioButton94);
        jRadioButton94.setName("jRadioButton94"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        jPanel16.add(jRadioButton94, gridBagConstraints);

        buttonGroup16.add(jRadioButton95);
        jRadioButton95.setName("jRadioButton95"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        jPanel16.add(jRadioButton95, gridBagConstraints);

        buttonGroup16.add(jRadioButton96);
        jRadioButton96.setSelected(true);
        jRadioButton96.setName("jRadioButton96"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        jPanel16.add(jRadioButton96, gridBagConstraints);

        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 15;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 7;
        gridBagConstraints.anchor = GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new Insets(10, 0, 0, 0);
        jPanelB.add(jPanel16, gridBagConstraints);

        jLabel1.setText("List files structure");
        jLabel1.setName("jLabel1"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.anchor = GridBagConstraints.WEST;
        jPanelB.add(jLabel1, gridBagConstraints);

        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = GridBagConstraints.NORTH;
        gridBagConstraints.insets = new Insets(0, 10, 0, 0);
        jPanelA.add(jPanelB, gridBagConstraints);

        jPanelC.setName("jPanelC"); // NOI18N
        jPanelC.setLayout(new GridBagLayout());

        jLabel16.setText("Output files");
        jLabel16.setName("jLabel16"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = GridBagConstraints.NORTHWEST;
        jPanelC.add(jLabel16, gridBagConstraints);

        jCheckBox1.setSelected(true);
        jCheckBox1.setText("Sorted Listfiles");
        jCheckBox1.setName("jCheckBox1"); // NOI18N
        jCheckBox1.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = GridBagConstraints.WEST;
        jPanelC.add(jCheckBox1, gridBagConstraints);

        jCheckBox2.setSelected(true);
        jCheckBox2.setText("Gupix - Singles");
        jCheckBox2.setName("jCheckBox2"); // NOI18N
        jCheckBox2.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = GridBagConstraints.WEST;
        jPanelC.add(jCheckBox2, gridBagConstraints);

        jCheckBox3.setSelected(true);
        jCheckBox3.setText("Gupix - Sum");
        jCheckBox3.setName("jCheckBox3"); // NOI18N
        jCheckBox3.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = GridBagConstraints.WEST;
        jPanelC.add(jCheckBox3, gridBagConstraints);

        jCheckBox4.setText("SimNRA");
        jCheckBox4.setName("jCheckBox4"); // NOI18N
        jCheckBox4.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jCheckBox4ActionPerformed(evt);
            }
        });
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = GridBagConstraints.WEST;
        jPanelC.add(jCheckBox4, gridBagConstraints);

        jLabel18.setText("Save");
        jLabel18.setName("jLabel18"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = GridBagConstraints.WEST;
        gridBagConstraints.insets = new Insets(10, 5, 0, 0);
        jPanelC.add(jLabel18, gridBagConstraints);

        jCheckBox5.setText("STIM-J");
        jCheckBox5.setName("jCheckBox5"); // NOI18N
        jCheckBox5.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jCheckBox5ActionPerformed(evt);
            }
        });
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = GridBagConstraints.WEST;
        jPanelC.add(jCheckBox5, gridBagConstraints);

        jLabel19.setText("Display");
        jLabel19.setName("jLabel19"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = GridBagConstraints.WEST;
        gridBagConstraints.insets = new Insets(10, 5, 0, 0);
        jPanelC.add(jLabel19, gridBagConstraints);

        jCheckBox6.setText("STIM map");
        jCheckBox6.setName("jCheckBox6"); // NOI18N
        jCheckBox6.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jCheckBox6ActionPerformed(evt);
            }
        });
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = GridBagConstraints.WEST;
        gridBagConstraints.insets = new Insets(0, 0, 0, 10);
        jPanelC.add(jCheckBox6, gridBagConstraints);

        jCheckBox7.setText("spectra");
        jCheckBox7.setName("jCheckBox7"); // NOI18N
        jCheckBox7.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jCheckBox7ActionPerformed(evt);
            }
        });
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = GridBagConstraints.LINE_START;
        jPanelC.add(jCheckBox7, gridBagConstraints);

        jLabel20.setText("Calculate");
        jLabel20.setName("jLabel20"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new Insets(10, 5, 0, 0);
        jPanelC.add(jLabel20, gridBagConstraints);

        jCheckBox8.setText("SupaVisio");
        jCheckBox8.setEnabled(false);
        jCheckBox8.setName("jCheckBox8"); // NOI18N
        jCheckBox8.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jCheckBox8ActionPerformed(evt);
            }
        });
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new Insets(0, 5, 0, 0);
        jPanelC.add(jCheckBox8, gridBagConstraints);

        jCheckBox9.setText("STIM stack");
        jCheckBox9.setName("jCheckBox9"); // NOI18N
        jCheckBox9.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jCheckBox9ActionPerformed(evt);
            }
        });
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = GridBagConstraints.LINE_START;
        jPanelC.add(jCheckBox9, gridBagConstraints);

        jCheckBox10.setText("PIXE maps");
        jCheckBox10.setEnabled(false);
        jCheckBox10.setName("jCheckBox10"); // NOI18N
        jCheckBox10.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jCheckBox10ActionPerformed(evt);
            }
        });
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = GridBagConstraints.LINE_START;
        jPanelC.add(jCheckBox10, gridBagConstraints);

        jCheckBox11.setText("<html>Tomo PIXE<br> proj. sum</html>");
        jCheckBox11.setName("jCheckBox11"); // NOI18N
        jCheckBox11.setVerticalTextPosition(SwingConstants.TOP);
        jCheckBox11.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jCheckBox11ActionPerformed(evt);
            }
        });
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = GridBagConstraints.FIRST_LINE_START;
        jPanelC.add(jCheckBox11, gridBagConstraints);

        jCheckBox12.setText("STIM stack");
        jCheckBox12.setName("jCheckBox12"); // NOI18N
        jCheckBox12.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jCheckBox12ActionPerformed(evt);
            }
        });
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = GridBagConstraints.LINE_START;
        jPanelC.add(jCheckBox12, gridBagConstraints);

        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new Insets(20, 10, 0, 0);
        jPanelA.add(jPanelC, gridBagConstraints);

        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new Insets(20, 20, 20, 20);
        getContentPane().add(jPanelA, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // flag for button PIXE-singles (17)
    private void jCheckBox2ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        int flag=17;
        AbstractButton AB = (AbstractButton) evt.getSource();
        if (AB.getModel().isSelected()) act.setFlags(flag,1);
	else { 
            act.setFlags(flag,0);
            /*if (!(jCheckBox3.isSelected())){
                jCheckBox11.setSelected(false);
                act.setFlags(16,0);
            }*/
        }
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    // Flag for median map (21)
    private void jCheckBox6ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jCheckBox6ActionPerformed
        int flag=21;
        AbstractButton AB = (AbstractButton) evt.getSource();
	if (AB.getModel().isSelected()) act.setFlags(flag,1);
	else act.setFlags(flag,0);
    }//GEN-LAST:event_jCheckBox6ActionPerformed
    // Set flag for sorting events (16)
    private void jCheckBox1ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        int flag=16;
        AbstractButton AB = (AbstractButton) evt.getSource();
        if (AB.getModel().isSelected()) act.setFlags(flag,1);
	else act.setFlags(flag,0);
    }//GEN-LAST:event_jCheckBox1ActionPerformed
    // Checkbox Sum PIXE spectra (18)
    private void jCheckBox3ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
        int flag=18;
        AbstractButton AB = (AbstractButton) evt.getSource();
	if (AB.getModel().isSelected()) act.setFlags(flag,1);
	else act.setFlags(flag,0);
    }//GEN-LAST:event_jCheckBox3ActionPerformed
    // SimNRA (19)
    private void jCheckBox4ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jCheckBox4ActionPerformed
        int flag=19;
        AbstractButton AB = (AbstractButton) evt.getSource();
	if (AB.getModel().isSelected()) act.setFlags(flag,1);
	else act.setFlags(flag,0);
    }//GEN-LAST:event_jCheckBox4ActionPerformed
    // STIM-J (20)
    private void jCheckBox5ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jCheckBox5ActionPerformed
        int flag=20;
        AbstractButton AB = (AbstractButton) evt.getSource();
	if (AB.getModel().isSelected()) act.setFlags(flag,1);
	else act.setFlags(flag,0);
    }//GEN-LAST:event_jCheckBox5ActionPerformed
    // SupaVisio readable (XYE) listfiles type (27)
    private void jCheckBox8ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jCheckBox8ActionPerformed
        int flag=27;
        AbstractButton AB = (AbstractButton) evt.getSource();
	if (AB.getModel().isSelected()) act.setFlags(flag,1);
	else act.setFlags(flag,0);
    }//GEN-LAST:event_jCheckBox8ActionPerformed
    // Display spectra (22)
    private void jCheckBox7ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jCheckBox7ActionPerformed
        int flag=22;
        AbstractButton AB = (AbstractButton) evt.getSource();
	if (AB.getModel().isSelected()) act.setFlags(flag,1);
	else act.setFlags(flag,0);        
    }//GEN-LAST:event_jCheckBox7ActionPerformed
    // Display STIM map (23)
    private void jCheckBox9ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jCheckBox9ActionPerformed
        int flag=23;
        AbstractButton AB = (AbstractButton) evt.getSource();
	if (AB.getModel().isSelected()) act.setFlags(flag,1);
	else act.setFlags(flag,0);        
    }//GEN-LAST:event_jCheckBox9ActionPerformed
    // PIXE map calculation (26)
    private void jCheckBox10ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jCheckBox10ActionPerformed
        int flag=26;
        AbstractButton AB = (AbstractButton) evt.getSource();
        if (AB.getModel().isSelected()) {
            act.setFlags(flag,1);
            
        }
	else act.setFlags(flag,0);        
    }//GEN-LAST:event_jCheckBox10ActionPerformed
    // Checkbox for pixe stack (24)
    private void jCheckBox11ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jCheckBox11ActionPerformed
        int flag=24;
        AbstractButton AB = (AbstractButton) evt.getSource();
	if (AB.getModel().isSelected()){
            act.setFlags(flag,1);
            /*if (!(jCheckBox2.isSelected())&&!(jCheckBox3.isSelected())){
                jCheckBox2.setSelected(true);
                act.setFlags(9,1);
            }*/
        }
	else act.setFlags(flag,0);
    }//GEN-LAST:event_jCheckBox11ActionPerformed
    // STIM map stack calculation (25)
    private void jCheckBox12ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jCheckBox12ActionPerformed
        int flag=25;
        AbstractButton AB = (AbstractButton) evt.getSource();
	if (AB.getModel().isSelected()) act.setFlags(flag,1);
	else act.setFlags(flag,0);
    }//GEN-LAST:event_jCheckBox12ActionPerformed
    /**
     * This method is used to open a lst file and will save the resulting pixe, rbs or stim file
     */
    public void openLST() {                                         
        act.reset();
	act.setFlags(this);
        act.selectFiles();
	act.process();
	java.lang.System.gc();
    }    

	
    private final ActionsC act=new ActionsC();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ButtonGroup buttonGroup1;
    private ButtonGroup buttonGroup10;
    private ButtonGroup buttonGroup11;
    private ButtonGroup buttonGroup12;
    private ButtonGroup buttonGroup13;
    private ButtonGroup buttonGroup14;
    private ButtonGroup buttonGroup15;
    private ButtonGroup buttonGroup16;
    private ButtonGroup buttonGroup2;
    private ButtonGroup buttonGroup3;
    private ButtonGroup buttonGroup4;
    private ButtonGroup buttonGroup5;
    private ButtonGroup buttonGroup6;
    private ButtonGroup buttonGroup7;
    private ButtonGroup buttonGroup8;
    private ButtonGroup buttonGroup9;
    private JCheckBox jCheckBox1;
    private JCheckBox jCheckBox10;
    private JCheckBox jCheckBox11;
    private JCheckBox jCheckBox12;
    private JCheckBox jCheckBox2;
    private JCheckBox jCheckBox3;
    private JCheckBox jCheckBox4;
    private JCheckBox jCheckBox5;
    private JCheckBox jCheckBox6;
    private JCheckBox jCheckBox7;
    private JCheckBox jCheckBox8;
    private JCheckBox jCheckBox9;
    private JLabel jLabel1;
    private JLabel jLabel10;
    private JLabel jLabel11;
    private JLabel jLabel12;
    private JLabel jLabel13;
    private JLabel jLabel14;
    private JLabel jLabel15;
    private JLabel jLabel16;
    private JLabel jLabel17;
    private JLabel jLabel18;
    private JLabel jLabel19;
    private JLabel jLabel2;
    private JLabel jLabel20;
    private JLabel jLabel21;
    private JLabel jLabel22;
    private JLabel jLabel23;
    private JLabel jLabel24;
    private JLabel jLabel25;
    private JLabel jLabel26;
    private JLabel jLabel27;
    private JLabel jLabel28;
    private JLabel jLabel3;
    private JLabel jLabel4;
    private JLabel jLabel5;
    private JLabel jLabel6;
    private JLabel jLabel7;
    private JLabel jLabel8;
    private JLabel jLabel9;
    public JPanel jPanel1;
    public JPanel jPanel10;
    public JPanel jPanel11;
    public JPanel jPanel12;
    public JPanel jPanel13;
    public JPanel jPanel14;
    public JPanel jPanel15;
    public JPanel jPanel16;
    public JPanel jPanel2;
    public JPanel jPanel3;
    public JPanel jPanel4;
    public JPanel jPanel5;
    public JPanel jPanel6;
    public JPanel jPanel7;
    public JPanel jPanel8;
    public JPanel jPanel9;
    public JPanel jPanelA;
    public JPanel jPanelB;
    private JPanel jPanelC;
    private JRadioButton jRadioButton1;
    private JRadioButton jRadioButton10;
    private JRadioButton jRadioButton11;
    private JRadioButton jRadioButton12;
    private JRadioButton jRadioButton13;
    private JRadioButton jRadioButton14;
    private JRadioButton jRadioButton15;
    private JRadioButton jRadioButton16;
    private JRadioButton jRadioButton17;
    private JRadioButton jRadioButton18;
    private JRadioButton jRadioButton19;
    private JRadioButton jRadioButton2;
    private JRadioButton jRadioButton20;
    private JRadioButton jRadioButton21;
    private JRadioButton jRadioButton22;
    private JRadioButton jRadioButton23;
    private JRadioButton jRadioButton24;
    private JRadioButton jRadioButton25;
    private JRadioButton jRadioButton26;
    private JRadioButton jRadioButton27;
    private JRadioButton jRadioButton28;
    private JRadioButton jRadioButton29;
    private JRadioButton jRadioButton3;
    private JRadioButton jRadioButton30;
    private JRadioButton jRadioButton31;
    private JRadioButton jRadioButton32;
    private JRadioButton jRadioButton33;
    private JRadioButton jRadioButton34;
    private JRadioButton jRadioButton35;
    private JRadioButton jRadioButton36;
    private JRadioButton jRadioButton37;
    private JRadioButton jRadioButton38;
    private JRadioButton jRadioButton39;
    private JRadioButton jRadioButton4;
    private JRadioButton jRadioButton40;
    private JRadioButton jRadioButton41;
    private JRadioButton jRadioButton42;
    private JRadioButton jRadioButton43;
    private JRadioButton jRadioButton44;
    private JRadioButton jRadioButton45;
    private JRadioButton jRadioButton46;
    private JRadioButton jRadioButton47;
    private JRadioButton jRadioButton48;
    private JRadioButton jRadioButton49;
    private JRadioButton jRadioButton5;
    private JRadioButton jRadioButton50;
    private JRadioButton jRadioButton51;
    private JRadioButton jRadioButton52;
    private JRadioButton jRadioButton53;
    private JRadioButton jRadioButton54;
    private JRadioButton jRadioButton55;
    private JRadioButton jRadioButton56;
    private JRadioButton jRadioButton57;
    private JRadioButton jRadioButton58;
    private JRadioButton jRadioButton59;
    private JRadioButton jRadioButton6;
    private JRadioButton jRadioButton60;
    private JRadioButton jRadioButton61;
    private JRadioButton jRadioButton62;
    private JRadioButton jRadioButton63;
    private JRadioButton jRadioButton64;
    private JRadioButton jRadioButton65;
    private JRadioButton jRadioButton66;
    private JRadioButton jRadioButton67;
    private JRadioButton jRadioButton68;
    private JRadioButton jRadioButton69;
    private JRadioButton jRadioButton7;
    private JRadioButton jRadioButton70;
    private JRadioButton jRadioButton71;
    private JRadioButton jRadioButton72;
    private JRadioButton jRadioButton73;
    private JRadioButton jRadioButton74;
    private JRadioButton jRadioButton75;
    private JRadioButton jRadioButton76;
    private JRadioButton jRadioButton77;
    private JRadioButton jRadioButton78;
    private JRadioButton jRadioButton79;
    private JRadioButton jRadioButton8;
    private JRadioButton jRadioButton80;
    private JRadioButton jRadioButton81;
    private JRadioButton jRadioButton82;
    private JRadioButton jRadioButton83;
    private JRadioButton jRadioButton84;
    private JRadioButton jRadioButton85;
    private JRadioButton jRadioButton86;
    private JRadioButton jRadioButton87;
    private JRadioButton jRadioButton88;
    private JRadioButton jRadioButton89;
    private JRadioButton jRadioButton9;
    private JRadioButton jRadioButton90;
    private JRadioButton jRadioButton91;
    private JRadioButton jRadioButton92;
    private JRadioButton jRadioButton93;
    private JRadioButton jRadioButton94;
    private JRadioButton jRadioButton95;
    private JRadioButton jRadioButton96;
    // End of variables declaration//GEN-END:variables
}
